// App Constants and Translations

export const LANGUAGES = {
  en: 'English',
  hi: 'हिंदी',
  kn: 'ಕನ್ನಡ',
  ta: 'தமிழ்'
};

export const TRANSLATIONS = {
  en: {
    appName: 'Sahaaya',
    welcome: 'Welcome',
    home: 'Home',
    medications: 'Medications',
    emergency: 'Emergency',
    settings: 'Settings',
    profile: 'Profile',
    sos: 'SOS',
    addMedication: 'Add Medication',
    medicationName: 'Medicine Name',
    dosage: 'Dosage',
    time: 'Time',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    emergencyContacts: 'Emergency Contacts',
    addContact: 'Add Contact',
    contactName: 'Contact Name',
    phoneNumber: 'Phone Number',
    callNow: 'Call Now',
    sendSMS: 'Send SMS',
    myLocation: 'My Location',
    darkMode: 'Dark Mode',
    language: 'Language',
    voiceAssistant: 'Voice Assistant',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    enterPhone: 'Enter Phone Number',
    enterOTP: 'Enter OTP',
    verify: 'Verify',
    resendOTP: 'Resend OTP',
    takeMedicine: 'Time to take your medicine!',
    medicationReminder: 'Medication Reminder',
    emergencyAlert: 'Emergency! Sending your location...',
    locationShared: 'Location shared with emergency contacts',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    night: 'Night',
    daily: 'Daily',
    weekly: 'Weekly',
    asNeeded: 'As Needed'
  },
  hi: {
    appName: 'सहाय',
    welcome: 'स्वागत है',
    home: 'होम',
    medications: 'दवाइयाँ',
    emergency: 'आपातकाल',
    settings: 'सेटिंग',
    profile: 'प्रोफाइल',
    sos: 'एसओएस',
    addMedication: 'दवा जोड़ें',
    medicationName: 'दवा का नाम',
    dosage: 'खुराक',
    time: 'समय',
    save: 'सेव करें',
    cancel: 'रद्द करें',
    delete: 'मिटाएं',
    edit: 'संपादित करें',
    emergencyContacts: 'आपातकालीन संपर्क',
    addContact: 'संपर्क जोड़ें',
    contactName: 'संपर्क का नाम',
    phoneNumber: 'फोन नंबर',
    callNow: 'अभी कॉल करें',
    sendSMS: 'एसएमएस भेजें',
    myLocation: 'मेरा स्थान',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    voiceAssistant: 'वॉइस असिस्टेंट',
    logout: 'लॉगआउट',
    login: 'लॉगिन',
    register: 'रजिस्टर करें',
    enterPhone: 'फोन नंबर दर्ज करें',
    enterOTP: 'ओटीपी दर्ज करें',
    verify: 'सत्यापित करें',
    resendOTP: 'ओटीपी फिर से भेजें',
    takeMedicine: 'दवा लेने का समय!',
    medicationReminder: 'दवा याद दिलाना',
    emergencyAlert: 'आपातकाल! आपका स्थान भेजा जा रहा है...',
    locationShared: 'आपातकालीन संपर्कों के साथ स्थान साझा किया गया',
    morning: 'सुबह',
    afternoon: 'दोपहर',
    evening: 'शाम',
    night: 'रात',
    daily: 'रोज़ाना',
    weekly: 'साप्ताहिक',
    asNeeded: 'जरूरत पर'
  },
  kn: {
    appName: 'ಸಹಾಯ',
    welcome: 'ಸ್ವಾಗತ',
    home: 'ಮುಖಪುಟ',
    medications: 'ಔಷಧಗಳು',
    emergency: 'ತುರ್ತು',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',
    sos: 'ಎಸ್‌ಓಎಸ್',
    addMedication: 'ಔಷಧ ಸೇರಿಸಿ',
    medicationName: 'ಔಷಧದ ಹೆಸರು',
    dosage: 'ಡೋಸೇಜ್',
    time: 'ಸಮಯ',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಗೊಳಿಸಿ',
    delete: 'ಅಳಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    emergencyContacts: 'ತುರ್ತು ಸಂಪರ್�ಗಳು',
    addContact: 'ಸಂಪರ್ಕ ಸೇರಿಸಿ',
    contactName: 'ಸಂಪರ್ಕದ ಹೆಸರು',
    phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    callNow: 'ಈಗ ಕರೆ ಮಾಡಿ',
    sendSMS: 'ಎಸ್‌ಎಂಎಸ್ ಕಳುಹಿಸಿ',
    myLocation: 'ನನ್ನ ಸ್ಥಳ',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    language: 'ಭಾಷೆ',
    voiceAssistant: 'ವಾಯ್ಸ್ ಅಸಿಸ್ಟೆಂಟ್',
    logout: 'ಲಾಗ್‌ಔಟ್',
    login: 'ಲಾಗಿನ್',
    register: 'ನೋಂದಣಿ',
    enterPhone: 'ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    enterOTP: 'ಒಟಿಪಿ ನಮೂದಿಸಿ',
    verify: 'ಪರಿಶೀಲಿಸಿ',
    resendOTP: 'ಒಟಿಪಿ ಮರು ಕಳುಹಿಸಿ',
    takeMedicine: 'ಔಷಧ ತೆಗೆದುಕೊಳ್ಳುವ ಸಮಯ!',
    medicationReminder: 'ಔಷಧ ಜ್ಞಾಪನೆ',
    emergencyAlert: 'ತುರ್ತು! ನಿಮ್ಮ ಸ್ಥಳ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...',
    locationShared: 'ತುರ್ತು ಸಂಪರ್ಕಗಳೊಂದಿಗೆ ಸ್ಥಳ ಹಂಚಿಕೊಳ್ಳಲಾಗಿದೆ',
    morning: 'ಬೆಳಿಗ್ಗೆ',
    afternoon: 'ಮಧ್ಯಾಹ್ನ',
    evening: 'ಸಂಜೆ',
    night: 'ರಾತ್ರಿ',
    daily: 'ದೈನಂದಿನ',
    weekly: 'ಸಾಪ್ತಾಹಿಕ',
    asNeeded: 'ಅಗತ್ಯವಿದ್ದಾಗ'
  },
  ta: {
    appName: 'சஹாயா',
    welcome: 'வரவேற்பு',
    home: 'முகப்பு',
    medications: 'மருந்துகள்',
    emergency: 'அவசரம்',
    settings: 'அமைப்புகள்',
    profile: 'சுயவிவரம்',
    sos: 'எஸ்.ஓ.எஸ்',
    addMedication: 'மருந்து சேர்க்கவும்',
    medicationName: 'மருந்தின் பெயர்',
    dosage: 'அளவு',
    time: 'நேரம்',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    emergencyContacts: 'அவசர தொடர்புகள்',
    addContact: 'தொடர்பு சேர்க்கவும்',
    contactName: 'தொடர்பு பெயர்',
    phoneNumber: 'தொலைபேசி எண்',
    callNow: 'இப்போது அழைக்கவும்',
    sendSMS: 'குறுஞ்செய்தி அனுப்பவும்',
    myLocation: 'எனது இருப்பிடம்',
    darkMode: 'இருண்ட பயன்முறை',
    language: 'மொழி',
    voiceAssistant: 'குரல் உதவியாளர்',
    logout: 'வெளியேறு',
    login: 'உள்நுழைவு',
    register: 'பதிவு செய்க',
    enterPhone: 'தொலைபேசி எண்ணை உள்ளிடவும்',
    enterOTP: 'OTP ஐ உள்ளிடவும்',
    verify: 'சரிபார்க்கவும்',
    resendOTP: 'OTP ஐ மீண்டும் அனுப்பவும்',
    takeMedicine: 'மருந்து எடுக்கும் நேரம்!',
    medicationReminder: 'மருந்து நினைவூட்டல்',
    emergencyAlert: 'அவசரம்! உங்கள் இருப்பிடம் அனுப்பப்படுகிறது...',
    locationShared: 'அவசர தொடர்புகளுடன் இருப்பிடம் பகிரப்பட்டது',
    morning: 'காலை',
    afternoon: 'பிற்பகல்',
    evening: 'மாலை',
    night: 'இரவு',
    daily: 'தினசரி',
    weekly: 'வாராந்திர',
    asNeeded: 'தேவைப்படும்போது'
  }
};

export const COLORS = {
  light: {
    primary: '#4A90E2',
    secondary: '#50C878',
    danger: '#E74C3C',
    background: '#FFFFFF',
    text: '#000000',
    card: '#F5F5F5',
    border: '#DDDDDD',
    success: '#28A745',
    warning: '#FFC107',
    info: '#17A2B8'
  },
  dark: {
    primary: '#5FA3E8',
    secondary: '#5DD68D',
    danger: '#F05A4A',
    background: '#121212',
    text: '#FFFFFF',
    card: '#1E1E1E',
    border: '#333333',
    success: '#34C759',
    warning: '#FFD60A',
    info: '#30D5F0'
  }
};

export const MEDICATION_TIMES = [
  { label: 'Morning (8:00 AM)', value: '08:00' },
  { label: 'Afternoon (12:00 PM)', value: '12:00' },
  { label: 'Evening (6:00 PM)', value: '18:00' },
  { label: 'Night (10:00 PM)', value: '22:00' }
];

export const FONT_SIZES = {
  small: 18,
  medium: 24,
  large: 32,
  xlarge: 40
};